SELECT
				BBR_Aktiv_Enhed.KommuneNr,
				BBR_Aktiv_Enhed.Ejendomsnummer,
				BBR_Aktiv_Enhed.BFEnr,
				BBR_Aktiv_Enhed.Ejendomstype,
				BBR_Aktiv_Enhed.EnhedensAnvendelseKode,
				BBR_Aktiv_Enhed.EnhedensAnvendelse,
				BBR_Aktiv_Enhed.BoligtypeKode,
				BBR_Aktiv_Enhed.Boligtype,
				DAR_AKTIVE_ADRESSER.Enh_Adresse,
				DAR_AKTIVE_ADRESSER.VejNavn + ' ' + DAR_AKTIVE_ADRESSER.Husnummer AS Adgangsadresse,
				DAR_AKTIVE_ADRESSER.ByNavn,
				DAR_AKTIVE_ADRESSER.PostNr,
				DAR_AKTIVE_ADRESSER.Postdistrikt,
				BBR_Aktiv_Enhed.EnhedensSamledeAreal,
				BBR_Aktiv_Enhed.ArealTilBeboelse,
				BBR_Aktiv_Enhed.ArealTilErhverv,
				BBR_Aktiv_Enhed.AndetAreal,
				BBR_Aktiv_Enhed.ArealAfaabenOverdaekning,
				BBR_Aktiv_Enhed.ArealLukketOverdaekningUdestue,
				BBR_Aktiv_Enhed.KildeTilEnhedensArealerKode,
				BBR_Aktiv_Enhed.KildeTilEnhedensArealer,
				BBR_Aktiv_Enhed.EnhedAndelFaellesAdgangsareal,
				BBR_Aktiv_Enhed.AabenAltanTagterrasseAreal,
				BBR_Aktiv_Enhed.AntalVaerelser,
				BBR_Aktiv_Enhed.AntalVaerelserTilErhverv,
				BBR_Aktiv_Enhed.ToiletforholdKode,
				BBR_Aktiv_Enhed.Toiletforhold,
				BBR_Aktiv_Enhed.BadeforholdKode,
				BBR_Aktiv_Enhed.Badeforhold,
				BBR_Aktiv_Enhed.AntalVandskylledeToiletter,
				BBR_Aktiv_Enhed.AntalBadevaerelser,
				BBR_Aktiv_Enhed.KoekkenforholdKode,
				BBR_Aktiv_Enhed.Koekkenforhold,
				BBR_Aktiv_Enhed.EnergiforsyningKode,
				BBR_Aktiv_Enhed.Energiforsyning,
				BBR_Aktiv_Enhed.VarmeinstallationKode,
				BBR_Aktiv_Enhed.Varmeinstallation,
				BBR_Aktiv_Enhed.OpvarmningsmiddelKode,
				BBR_Aktiv_Enhed.Opvarmningsmiddel,
				BBR_Aktiv_Enhed.SupplerendeVarmeKode,
				BBR_Aktiv_Enhed.SupplerendeVarme,
				BBR_Aktiv_Enhed.StoejisoleringAar,
				BBR_Aktiv_Enhed.LovligAnvendelseKode,
				BBR_Aktiv_Enhed.LovligAnvendelse,
				BBR_Aktiv_Enhed.UdlejningsforholdKode,
				BBR_Aktiv_Enhed.Udlejningsforhold,
				BBR_Aktiv_Enhed.OffentligStoetteKode,
				BBR_Aktiv_Enhed.OffentligStoette,
				BBR_Aktiv_Enhed.GodkendtTomBoligKode,
				BBR_Aktiv_Enhed.GodkendtTomBolig,
				BBR_Aktiv_Enhed.KondemneretBoligenhedKode,
				BBR_Aktiv_Enhed.KondemneretBoligenhed,
				BBR_Aktiv_Enhed.FlexboligTilladelsesartKode,
				BBR_Aktiv_Enhed.FlexboligTilladelsesart,
				BBR_Aktiv_Enhed.FlexboligOphoersdato,
				BBR_Aktiv_Enhed.IndflytningDato,
				BBR_Aktiv_Enhed.DatoTidsbegraensetDispensation,
				BBR_Aktiv_Enhed.DatoDelvisIbrugtaningTillad,
				BBR_Aktiv_Enhed.OprettelsesdatoForEnhedensId,
				BBR_Aktiv_Enhed.Gyldighedsdato,
				BBR_Aktiv_Enhed.HerafAreal1,
				BBR_Aktiv_Enhed.HerafAreal2,
				BBR_Aktiv_Enhed.HerafAreal3,
				BBR_Aktiv_Enhed.SupplerendeAnvendelseskode1,
				BBR_Aktiv_Enhed.SupplerendeAnvendelse1,
				BBR_Aktiv_Enhed.SupplerendeAnvendelseskode2,
				BBR_Aktiv_Enhed.SupplerendeAnvendelse2,
				BBR_Aktiv_Enhed.SupplerendeAnvendelseskode3,
				BBR_Aktiv_Enhed.SupplerendeAnvendelse3,
				BBR_Aktiv_Enhed.FysiskArealTilBeboelse,
				BBR_Aktiv_Enhed.FysiskArealTilErhverv,
				BBR_Aktiv_Enhed.AdresseFunktionKode,
				CAST(BBR_Aktiv_Enhed.ModerlejlighedID AS VARCHAR(38)) AS ModerlejlighedID,
				CAST(BBR_Aktiv_Enhed.AdresseID AS VARCHAR(38)) AS AdresseID,
				CAST(BBR_Aktiv_Enhed.HusnummerID AS VARCHAR(38)) AS HusnummerID,
				CAST(BBR_Aktiv_Enhed.EnhedID AS VARCHAR(38)) AS EnhedID,
				CAST(BBR_Aktiv_Enhed.BygningID AS VARCHAR(38)) AS BygningID,
				CAST(BBR_Aktiv_Enhed.OpgangID AS VARCHAR(38)) AS OpgangID,
				CAST(BBR_Aktiv_Enhed.EtageID AS VARCHAR(38)) AS EtageID,
				CAST(BBR_Aktiv_Enhed.BestemtFastEjendomID AS VARCHAR(38)) AS BestemtFastEjendomID,
				CAST(BBR_Aktiv_Enhed.zId AS VARCHAR(38)) AS zID,
				BBR_Aktiv_Enhed.TS,
				BBR_Aktiv_Enhed.zTs,
				BBR_Aktiv_Enhed.sTs,
				BBR_Aktiv_Enhed.iTs,
				BBR_Aktiv_Enhed.tTs,
				DAR_AKTIVE_ADRESSEPUNKTER.Geometri,
				CAST('Pen (1,2,0) Brush (1,0,16777215) Symbol (51,255,9,"MapInfo Symbols",0,0)' AS varchar(100)) AS MI_STYLE
FROM
				DAR_AKTIVE_ADRESSEPUNKTER RIGHT OUTER JOIN
				DAR_AKTIVE_ADRESSER ON DAR_AKTIVE_ADRESSEPUNKTER.AdressepunktID = DAR_AKTIVE_ADRESSER.AdressepunktID RIGHT OUTER JOIN
				BBR_Aktiv_Enhed ON DAR_AKTIVE_ADRESSER.HusnummerID = BBR_Aktiv_Enhed.HusnummerID