SELECT
				MAT_Aktiv_SamletFastEjendom.KommuneNr,
				Ejertabel.BFE_NUMMER,
				Ejertabel.Ejendomsbeliggenhed,
				Ejertabel.Ejers_navn,
				Ejertabel.Ejers_CO_navn,
				Ejertabel.Ejers_adresse,
				Ejertabel.Ejers_udvidede_adresse,
				Ejertabel.Postdistrikt,
				Ejertabel.Benyttelseskode,
				Ejertabel.Benyttelse,
				Ejertabel.Ejers_statuskode,
				Ejertabel.Ejerstatus,
				Ejertabel.Pensionistkode,
				Ejertabel.Pensioniststatus,
				Ejertabel.Lejeværdikode,
				Ejertabel.Lejeværdi,
				Ejertabel.Kode_for_adressebeskyttelse,
				Ejertabel.Adressebeskyttelse,
				Ejertabel.Slutseddeldato,
				Ejertabel.Skødedato,
				Ejertabel.Overtagelsesdato,
				Ejertabel.Overdragelsesmåde,
				Ejertabel.Købesum,
				Ejertabel.Køberandel,
				Ejertabel.Ejerandel,
				Ejertabel.Ejer_CPR_CVR,
				Ejertabel.Ejendomsareal,
				Ejertabel.Heraf_vejareal,
				Ejertabel.Vurderet_areal,
				Ejertabel.Heraf_vurderet_vejareal,
				Ejertabel.Ejerforholdskode,
				Ejertabel.Ejerforhold,
				Ejertabel.Antal_ejere,
				Ejertabel.Antal_lejligheder,
				Ejertabel.Moderejendomsnummer,
				Ejertabel.Adgang_til_offentlig_vej,
				Ejertabel.Admin_adressebeskyttelse,
				Ejertabel.Administrators_navn,
				Ejertabel.Administrators_CO_navn,
				Ejertabel.Administrators_adresse,
				Ejertabel.Administrators_udv_adresse,
				Ejertabel.Administrators_postdistrikt,
				Ejertabel.Administratornummer,
				Ejertabel.Administrators_CPR_CVR,
				Ejertabel.Administratorkode,
				Ejertabel.Administratorstatus,
				MAT_Aktiv_SamletFastEjendom.geometri,
				MAT_Aktiv_SamletFastEjendom.SFEObjectID AS MI_PRINX,
				CAST('Pen (1, 2, 0) Brush (1, 0, 16777215) Symbol (49,0,12)' AS char(150)) AS MI_STYLE
FROM
				(SELECT DISTINCT
				CO11800T.BFE_NUMMER,
				JY67500V_T.ABELIG AS Ejendomsbeliggenhed,
				JY64900V_T.ANAVN AS Ejers_navn,
				JY64900V_T.ACONAVN AS Ejers_CO_navn,
				JY64900V_T.AADRESS AS Ejers_adresse,
				JY64900V_T.AUDVADR AS Ejers_udvidede_adresse,
				JY64900V_T.APOST AS Postdistrikt,
				JY67500V_T.CBENYT AS Benyttelseskode,
				CAST(QL61500V_T.TEKST AS VARCHAR(70)) AS Benyttelse,
				JY64900V_T.CMSTAT AS Ejers_statuskode,
				CAST(QL63200V_T.TEKST AS VARCHAR(75)) AS Ejerstatus,
				JY64900V_T.CPENS AS Pensionistkode,
				CAST(QL63400V_T.TEKST AS VARCHAR(75)) AS Pensioniststatus,
				JY64900V_T.CLEJE AS Lejeværdikode,
				CAST(QL63500V_T.TEKST AS VARCHAR(75)) AS Lejeværdi,
				JY64900V_T.CBSKADR AS Kode_for_adressebeskyttelse,
				CAST(QL63600V_T.TEKST AS VARCHAR(75)) AS Adressebeskyttelse,
				JY64900V_T.DSLUTS AS Slutseddeldato,
				JY64900V_T.DSKOED AS Skødedato,
				JY64900V_T.DOVTG AS Overtagelsesdato,
				CAST(QL63700V_T.TEKST AS VARCHAR(75)) AS Overdragelsesmåde,
				JY64900V_T.BKOEBS AS Købesum,
				CAST(CAST(JY64900V_T.GKOETAEL AS varchar(6)) + '/' + CAST(JY64900V_T.GKOENAEV AS varchar(6)) AS varchar(12)) AS Køberandel,
				CAST(CAST(JY64900V_T.GEJTAEL AS varchar(6)) + '/' + CAST(JY64900V_T.GEJNAEV AS varchar(6)) AS varchar(12)) AS Ejerandel,
				JY64900V_T.DCPRCIR AS Ejer_CPR_CVR,
				JY67500V_T.FTOTAR AS Ejendomsareal,
				JY67500V_T.FTOTVEJ AS Heraf_vejareal,
				JY67500V_T.FARVUR AS Vurderet_areal,
				JY67500V_T.FVEJVUR AS Heraf_vurderet_vejareal,
				JY67500V_T.CEJFORH AS Ejerforholdskode,
				CAST(QL50000V_T.TEKST AS VARCHAR(133)) AS Ejerforhold,
				JY67500V_T.FEJER AS Antal_ejere,
				JY67500V_T.FLEJL AS Antal_lejligheder,
				JY67500V_T.EMODER AS Moderejendomsnummer,
				JY67500V_T.COFVEJ AS Adgang_til_offentlig_vej,
				JY67500V_T.CBSKADRA AS Admin_adressebeskyttelse,
				JY67500V_T.AANAVN AS Administrators_navn,
				JY67500V_T.AACONAVN AS Administrators_CO_navn,
				JY67500V_T.AAADRESS AS Administrators_adresse,
				JY67500V_T.AAUDVADR AS Administrators_udv_adresse,
				JY67500V_T.AAPOST AS Administrators_postdistrikt,
				JY67500V_T.EADMNR AS Administratornummer,
				JY67500V_T.DCPRADM AS Administrators_CPR_CVR,
				JY67500V_T.CADM AS Administratorkode,
				QL65000V_T.TEKST AS Administratorstatus
		FROM
				QL61500V_T LEFT OUTER JOIN
				QL63400V_T LEFT OUTER JOIN
				QL63700V_T RIGHT OUTER JOIN
				JY67500V_T INNER JOIN
				JY64900V_T INNER JOIN
				CO11800T ON JY64900V_T.EEJDNR = CO11800T.EJD_NR ON JY67500V_T.EEJDNR = JY64900V_T.EEJDNR ON QL63700V_T.KODE = JY64900V_T.COVMD ON QL63400V_T.KODE = JY64900V_T.CPENS LEFT OUTER JOIN
				QL63200V_T ON JY64900V_T.CMSTAT = QL63200V_T.KODE LEFT OUTER JOIN
				QL63500V_T ON JY64900V_T.CLEJE = QL63500V_T.KODE LEFT OUTER JOIN
				QL50000V_T ON JY64900V_T.CEJFORH = QL50000V_T.KODE LEFT OUTER JOIN
				QL63600V_T ON JY64900V_T.CBSKADR = QL63600V_T.KODE RIGHT OUTER JOIN
				QL65000V_T ON JY67500V_T.CADM = QL65000V_T.KODE RIGHT OUTER JOIN
				QL61000V_T ON JY67500V_T.CARTK = QL61000V_T.KODE ON QL61500V_T.KODE = JY67500V_T.CBENYT) AS Ejertabel
	RIGHT OUTER JOIN MAT_Aktiv_SamletFastEjendom ON Ejertabel.BFE_NUMMER = MAT_Aktiv_SamletFastEjendom.BFEnr